export const TRAIN_TYPES = ['Express', 'Intercity', 'Normal'];

export const TRAIN_STATUS = {
  ON_TIME: 'ON_TIME',
  DELAYED: 'DELAYED',
  CANCELLED: 'CANCELLED',
  DISRUPTED: 'DISRUPTED',
};

export const TRAIN_CLASSES = {
  FIRST: 'FIRST',
  SECOND: 'SECOND',
  THIRD: 'THIRD',
};

export const PASSENGER_TYPES = {
  ADULT: 'ADULT',
  CHILD: 'CHILD',
};

export const ISSUE_TYPES = {
  TRAIN_DELAY: 'TRAIN_DELAY',
  OVERCROWDING: 'OVERCROWDING',
  UNSAFE_CONDITION: 'UNSAFE_CONDITION',
  CLEANLINESS: 'CLEANLINESS',
  BROKEN_FACILITY: 'BROKEN_FACILITY',
  STAFF_SERVICE: 'STAFF_SERVICE',
  OTHER: 'OTHER',
};

export const ISSUE_SEVERITY = {
  LOW: 'LOW',
  MEDIUM: 'MEDIUM',
  HIGH: 'HIGH',
};

export const ISSUE_STATUS = {
  UNDER_REVIEW: 'UNDER_REVIEW',
  IN_PROGRESS: 'IN_PROGRESS',
  RESOLVED: 'RESOLVED',
};

export const BOOKING_STATUS = {
  PENDING_PAYMENT: 'PENDING_PAYMENT',
  CONFIRMED: 'CONFIRMED',
  CANCELLED: 'CANCELLED',
  EXPIRED: 'EXPIRED',
};

export const PAYMENT_STATUS = {
  PENDING: 'PENDING',
  PAID: 'PAID',
  FAILED: 'FAILED',
  REFUNDED: 'REFUNDED',
};

export const PAYMENT_METHODS = {
  DEMO_CARD: 'DEMO_CARD',
  CREDIT_DEBIT_CARD: 'CREDIT_DEBIT_CARD',
};
